# Generated by Django 2.1.2 on 2018-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
