# Generated by Django 2.1.2 on 2018-10-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb_back', '0003_noticia_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fotoUrl',
        ),
    ]
