# Generated by Django 2.1.2 on 2018-10-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb_back', '0004_remove_noticia_fotourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
